### ISSUE TITLE
Use StyleCI

### ISSUE THREAD

**Issue by dciancu** [TerrePorter/StringBladeCompiler#10]
Hello!

Just a friendly invitation to activate https://styleci.io for your project.

**Comment by TerrePorter** [comment]
Perhaps in the future, thanks for the suggestion.

**Comment by dciancu** [comment]
@TerrePorter it's free and it will format code according to PHP-FIG standards. I was extending your package and it's not very nice to work with code in all directions...

Anyway, thank for the package, great job!

**Comment by TerrePorter** [comment]
@danieliancu I have it bookmarked, but just a little swamped right now to really dig in to it.

Also, If you think any of your "extending of the package" changes could benefit the package as a whole, I'm open to looking at including them.

**Comment by dciancu** [comment]
@TerrePorter Thank you for the reply. I'm extending to implement a case specific use, but I'll give it some thinking to how I can generalize it.
