### ISSUE TITLE
Do not compile view file

### ISSUE THREAD

**Issue by ghost** [TerrePorter/StringBladeCompiler#12]
Hi, we are using your package for sending email using templates that are entered using the database. However, these views will always be different and our views directory is getting huge, and it's starting to give problems for the server.

Can you disable the creating of this compiled view file, or return the view path so we can immediately delete it, or create an option to delete it after usage.

**Comment by TerrePorter** [comment]
It sounds like a good idea to delete the cache file for the generated views.

Which version of StringBladeCompiler are you using?

**Comment by TerrePorter** [comment]
I've updated version 3.0 and 3.2, with new function setDeleteViewCacheAfterRender

Released versions, 3.0.1 and 3.2.1, should be able to do a composer update and pull in those version updates respectively.

I'm getting pulled away, so might be a bit before I can get the update for version 1 (Laravel 4.2) and 2 (Laravel 5.0).

An example for version 3+ of how I run the function,

```
Route::get('/test10', function (Request $request) {

    // set complier engine to delete the view cache after rendering
    View::getEngineFromStringKey('stringblade')->setDeleteViewCacheAfterRender(true);

    // you can also specify 'blade' and it will delete the cache files generated when using the file template instead of the string template

   return  view( ['template' => ' {{ $token }}', 'secondsTemplateCacheExpires' => 0], ['token' => 'test ' ] );
});
```

**Comment by TerrePorter** [comment]
@thijsdemaa Did that help fix the problem your having? I have not yet made it the other version of the compiler, if your not using v2.

**Comment by TerrePorter** [comment]
@thijsdemaa Woo Hooo... have you had a chance to try the changes out ?

**Comment by ghost** [comment]
Hi, @TerrePorter, I'm very sorry for getting back to you so late. I discovered the problem lied not within the package, but our project. We were compiling the texts twice, and that caused it to create a lot of view-files. However, the option to delete the file after compiling is very useful, and we will definitely use it. Thanks!

**Comment by TerrePorter** [comment]
@thijsdemaa ok, I just wanted to make sure and close this ticket out if it had fixed the problem. Thanks for getting back with me.
