### ISSUE TITLE
Class 'StringCompilerException' not found

### ISSUE THREAD

**Issue by netjordan** [TerrePorter/StringBladeCompiler#16]
In Laravel 5 I'm getting the following error (obviously I understand why this is appearing)

FatalErrorException in StringView.php line 68:
Class 'StringCompilerException' not found in StringView.php line 68

**Comment by TerrePorter** [comment]
@netjordan It looks like the StringCompilerException file is using a different namespace, Wpb\StringBladeCompiler\Exceptions vs Wpb\StringBladeCompiler

Can you test and see if changing the use statement in the StringView (https://github.com/TerrePorter/StringBladeCompiler/blob/2.0/src/Wpb/StringBladeCompiler/StringView.php#L11) to Wpb\StringBladeCompiler\Exceptions\StringCompilerException fixes the problem.

**Comment by TerrePorter** [comment]
fixed namespace for StringCompilerException
