### ISSUE TITLE
 Blade::directive() does not seem to work.

### ISSUE THREAD

**Issue by IvoDof** [TerrePorter/StringBladeCompiler#18]
When we use:

```
 Blade::directive('block', function($expression) {
            return "<?php echo "Hello world"; ?>";
        });
```

And have @block() in our string template, we import with.
`$view = view(['template' => $template])->with($variables);`

It does not seem to know the directive.
Even if we dd() inside the compileStatements function we get a empty $customDirectives.

Do i need to register the directive in a other way?

**Comment by TerrePorter** [comment]
If you want the directive in both normal blade file templates then you would use 

```
Blade::directive('block', function($expression) {
            return "<?php echo "Hello world"; ?>";
        });
```

For the string blade it would be ...

```
StringBlade::directive('block', function($expression) {
            return "<?php echo "Hello world"; ?>";
        });
```

If you want both FileTemplates and StringTemplates to use the directive then you will need something like this or you would need to duplicate the code for each directive.

```
StringBlade::directive('block', function($expression) {
                return Someclass::handler($expression);
});
Blade::directive('block', function($expression) {
            return Someclass::handler($expression);
});

// some class
class someclass () { 
   public function handler ($expression) {
      // do something then return the php string
      return "<?php echo "Hello world"; ?>";
   }
}
```

Let me know if that helps.

**Comment by IvoDof** [comment]
Sorry for the late response, it indeed solved it.

**Comment by TerrePorter** [comment]
Glad it solved the problem.
