### ISSUE TITLE
Call to undefined method Wpb\String_Blade_Compiler\Factory::startPush()

### ISSUE THREAD

**Issue by jhhazelaar** [TerrePorter/StringBladeCompiler#19]
After updating laravel I've got this error:
`Call to undefined method Wpb\String_Blade_Compiler\Factory::startPush() in [project_root]/storage/framework/views/956a4ed4204425c97c4b7ea75a71ed70b9dcbd67.php on line 3`

After some digging around I've found this pull request in laravel repos: https://github.com/laravel/framework/pull/12808

If you look at the file changes of this pull request: https://github.com/laravel/framework/pull/12808/files. There are four methods added: startPush, stopPush, extendPush and yieldPushContent.

These methods needs to be added to the factory. Otherwise you can't update laravel.

**Comment by TerrePorter** [comment]
Hi @jhhazelaar 
I'm assuming that your using the 3.2 version. I've updated the factory class and from what I can tell it is working. If you can test your code and let me know how it goes.

ref: https://github.com/TerrePorter/StringBladeCompiler/commit/73150aa67c37d5404d42ce5557d98f99b9b33ca6

**Comment by TerrePorter** [comment]
Hey @jhhazelaar Did you get a chance yet to try out the changes?

**Comment by jhhazelaar** [comment]
Oh sorry for the late response. Everything works fine now, thanks!

**Comment by TerrePorter** [comment]
@jhhazelaar Thanks for the reply. I've push out a new release with the code updates.
