### ISSUE TITLE
A version for Laravel 5.5

### ISSUE THREAD

**Issue by DominiqueFERET** [TerrePorter/StringBladeCompiler#23]
Hello,

Do you plan a version for Laravel 5.5 of your component ?

Best regards,

Dominique

**Comment by pdbreen** [comment]
@DominiqueFERET passing this link along as a possible work-around/alternative - https://laracasts.com/discuss/channels/general-discussion/render-template-from-blade-template-in-database

**Comment by DominiqueFERET** [comment]
@pdbreen Just a word to thank you for this trick. I have a very limited use of this feature but losing it would have been blocking.
Thanks again

**Comment by TerrePorter** [comment]
@DominiqueFERET FYI, if your still using the package released a Laravel 5.5 version today.
