### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by slava-vishnyakov** [TerrePorter/StringBladeCompiler#24]
Any plans to support Laravel 5.5?

This seems to work:
https://github.com/TerrePorter/StringBladeCompiler/compare/3.4...IT-swap:3.5
but it's probably a good idea to create 3.5 branch, but Pull Request doesn't seem to allow to do that

**Comment by TerrePorter** [comment]
I made a a new branch, https://github.com/TerrePorter/StringBladeCompiler/tree/3.5

I'll test it this weekend, and release a package

**Comment by TerrePorter** [comment]
oh, apparently there is another way to do something similar, see https://github.com/TerrePorter/StringBladeCompiler/issues/23

**Comment by TerrePorter** [comment]
@slava-vishnyakov I've merged your changes and released a version. Thanks for the code update, I have been swamped with stuff here and hadn't gotten to it.

**Comment by slava-vishnyakov** [comment]
Excellent, thank you very much! Your library is very helpful for me! Kudos! 👍
