### ISSUE TITLE
can't install it with laravel 5.5.14

### ISSUE THREAD

**Issue by triblax** [TerrePorter/StringBladeCompiler#27]
Hello,
I can't install it...
composer require "wpb/string-blade-compiler"
Using version ^3.5 for wpb/string-blade-compiler
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wpb/string-blade-compiler ^3.5 -> satisfiable by wpb/string-blade-compiler[3.5.1].
    - Conclusion: remove laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.14
    - wpb/string-blade-compiler 3.5.1 requires illuminate/view 5.1.* -> satisfiable by illuminate/view[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - don't install illuminate/view v5.1.1|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.13|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.16|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.2|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.20|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.22|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.25|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.28|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.30|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.31|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.41|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.6|don't install laravel/framework v5.5.14
    - don't install illuminate/view v5.1.8|don't install laravel/framework v5.5.14
    - Installation request for laravel/framework (locked at v5.5.14, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.14].

Installation failed, reverting ./composer.json to its original content.

**Comment by TerrePorter** [comment]
@triblax i've updated the composer.json to fix this error. Give it another try and let me know how it goes.
