### ISSUE TITLE
Call to undefined method Wpb\String_Blade_Compiler\Factory::renderWhen()

### ISSUE THREAD

**Issue by iturcanu** [TerrePorter/StringBladeCompiler#28]
Hi,
it seems that here haven't been implemented all methods and when I am calling @includeWhen from my blade template, I am getting this error.

Could you have a look?

Update: I have added the renderWhen function from  Iluminate/View/Factory class and everythign works just great.

Could you add to the repository please?

**Comment by TerrePorter** [comment]
@iturcanu Thanks for the information. I've updated the code base to include the renderWhen function.

**Comment by iturcanu** [comment]
@TerrePorter  thanks for the update, but it seems that these changes have been added to the 3.5 version of the  library, could you update and the 3.4 version as many applications are running on Laravel 5.4 and till update, it would be nice to use all functionality.

Please let me know if I can help you with this.
Best regards,
Ion

**Comment by TerrePorter** [comment]
@iturcanu ah sorry about that. i've got a busy week this week, but i'll try to work it in, unless you want to submit a pull request. It could be next weekend before i can get the time.

**Comment by iturcanu** [comment]
@TerrePorter , yes, no problem, I can add needed methods for the 3.4 branch just I can't clone this repository because I get the next message:
git@github.com:TerrePorter/StringBladeCompiler.git: No such file or directory
I guess I don't have needed access rights.

**Comment by TerrePorter** [comment]
@iturcanu i think you need to make a fork of the repo then make the changes, then submit a pull request merging your changed to the 3.4 branch

**Comment by TerrePorter** [comment]
opps wrong button
