### ISSUE TITLE
FatalErrorException Declaration of ...\StringBladeCompiler::compile($viewData)

### ISSUE THREAD

**Issue by holymp2006** [TerrePorter/StringBladeCompiler#29]
hi,
I tried to build a mail the way you described in [#21](https://github.com/TerrePorter/StringBladeCompiler/issues/21#issuecomment-265844310), but I get the error:

```
Symfony\Component\Debug\Exception\FatalErrorException: Declaration of Wpb\String_Blade_Compiler\Compilers\StringBladeCompiler::compile($viewData) must be compatible with Illuminate\View\Compilers\BladeCompiler::compile($path = NULL) in /.../vendor/wpb/string-blade-compiler/src/Compilers/StringBladeCompiler.php:8
Stack trace:
#0 {main}
```

I couldn't figure out the problem as the stack trace wasn't helpful.

**Comment by rafaelgou** [comment]
I have the same issue. It seems to be related to PHP 7.2 - works fine with 7.1.

I think it's more strict. Is that your case?

**Comment by holymp2006** [comment]
you're totally right, my version of php was the issue. everything was working fine until I switched to php 7.2 some days ago. I just switched back to 7.1 and everything's back to normal.

Any possible fix with php7.2?

**Comment by petermein** [comment]
Adding:
```
public function compile($viewData = null)
```
Should conform with the parent function, and then maybe throw an exception. 

I could make a PR if you like, but what exception would you like to be thrown in case no viewData is thrown?

**Comment by matthewscalf** [comment]
Any update here? Really need to get this fixed.

**Comment by JorgeDroid** [comment]
@petermein In which file do I need to add that code?

**Comment by TerrePorter** [comment]
merged https://github.com/TerrePorter/StringBladeCompiler/pull/35
