### ISSUE TITLE
Blade:extend

### ISSUE THREAD

**Issue by laurentlemaire** [TerrePorter/StringBladeCompiler#3]
How do you get the blade::extend to work?

I have a file containing several Blade:extend that is loaded in my global.php.
I've also tried to do it in my controller juste above the call to StringView::make but it doesn't take the blade extends into account.

Note that it works fine when working with the default Blade compiler...
Thx!

**Comment by TerrePorter** [comment]
To create a extend for the StringView,
```
StringView::extend(function( ...
```
I see that I uses Blade:extend in the readme. 

I'll up date the info readme as I see it can be misleading.

**Comment by TerrePorter** [comment]
I tend to do this when I need the same extend function in both Blade and StringView.

````
$func = function($value)
        {
            return preg_replace('/(\s*)@(break|continue)(\s*)/', '$1<?php $2; ?>$3', $value);
       };
Blade::extend($func);
StringView::extend($func);
```

**Comment by laurentlemaire** [comment]
Thanks!
