### ISSUE TITLE
Still use old view() function ?

### ISSUE THREAD

**Issue by nguyenanhthai** [TerrePorter/StringBladeCompiler#34]
I have followed installation steps, but not work. Someone help pls?

(1/1) ErrorExceptionstrpos() expects parameter 1 to be string, array given
--

**Comment by TerrePorter** [comment]
@nguyenanhthai What version are you using?

**Comment by pontoffeltier** [comment]
Same problem here. Using 3.4 with Laravel 5.4

**Comment by pontoffeltier** [comment]
Never mind, I forgot to add the ViewServiceProvider to my config/app.php -.-
