### ISSUE TITLE
Please add fix for PHP 7.2 to version 3.5

### ISSUE THREAD

**Issue by grahami** [TerrePorter/StringBladeCompiler#37]
Could we get the change in #35 in a release for the 3.5 version branch please?

**Comment by TerrePorter** [comment]
@grahami I've released 3.5.5 which has that change in it.

**Comment by laf** [comment]
Any chance this could be ported to 3.4 as well?

**Comment by TerrePorter** [comment]
@laf published a new release with this update for version 3.4

https://github.com/TerrePorter/StringBladeCompiler/releases/tag/3.4.2

**Comment by laf** [comment]
@TerrePorter Awesome (sorry for the delay). Thank you so much
