### ISSUE TITLE
New Version For Laravel 5.8 ?

### ISSUE THREAD

**Issue by gurinder-xyrintech** [TerrePorter/StringBladeCompiler#45]
just want to know when will b release of wpb new version for laravel 5.8

**Comment by mikerogne** [comment]
@gurinder-xyrintech branch 3.8 supports Laravel 5.8

**Comment by gurinder-xyrintech** [comment]
> @gurinder-xyrintech branch 3.8 supports Laravel 5.8

Thanku So much, i really need this
its working
