### ISSUE TITLE
Versions >3.6 are not available via Composer/Packagist

### ISSUE THREAD

**Issue by ianmcqueen** [TerrePorter/StringBladeCompiler#49]
Hello,

I'm attempting to install the version 3.7 branch from Composer but I notice that on Packagist, only up to version 3.6 is included.

Is there a way to push the latest versions to Composer/Packagist? Thanks in advanced!

Best,
Ian

**Comment by TerrePorter** [comment]
@ianmcqueen I had to reset up the hook to github. It should be updating now.

**Comment by ianmcqueen** [comment]
Fixed! Thank you!
