### ISSUE TITLE
Extending string layout

### ISSUE THREAD

**Issue by drnkwati** [TerrePorter/StringBladeCompiler#51]
Hi
Is it possible to extend a layout from string.
That is providing a layout as string and extending from it

**Comment by TerrePorter** [comment]
I don't think so at least not in the sense of using the @extends tag. I have not tried this, but you might be able to write a custom blade tag, then have that do what the normal @extends does, but with a string var that is being passed to the page. A custom extends tag more or less. I would have to refresh my memory on the code to confirm its possible but right now work has me stuck in WordPress land.
