### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by gjm** [TerrePorter/StringBladeCompiler#52]

**Comment by bretto36** [comment]
Seconded

**Comment by bretto36** [comment]
#53

**Comment by TerrePorter** [comment]
@gjm @bretto36 Sorry for the delay on getting this updated. [4.0](https://github.com/TerrePorter/StringBladeCompiler/tree/4.0) is now the Laravel 6 version. I will try to get my schedule worked around so that I can support it better.
