### ISSUE TITLE
Can't install in laravel 6.4

### ISSUE THREAD

**Issue by edwinencomienda** [TerrePorter/StringBladeCompiler#54]

**Comment by mediagraphik** [comment]
Same problem here, please make it accessible.

**Comment by vdauchy** [comment]
Hi @TerrePorter ,
Your fix was pushed to the 4.0 branch but was not tagged which force the use of the branch as: "wpb/string-blade-compiler": "4.0.x-dev" in composer.json.
Could you tag your latest changes as 4.0.1 for example so we can stick to tag tracking in composer ?
Thanks for your work :-)
