### ISSUE TITLE
Works in Laravel 7

### ISSUE THREAD

**Issue by kchoppin** [TerrePorter/StringBladeCompiler#57]
FYI. Just forked and bumped dep to Laravel 7, seems to work fine! 👍

**Comment by zhanang19** [comment]
Hello @kchoppin, have you try this package out compatible with Laravel 7 Component?
Thanks.

**Comment by ahmad-saad** [comment]
@TerrePorter ,

when it works fine in Laravel 7 as @kchoppin said, can you please change the dep to laravel 7

Thanks

**Comment by chris-rr** [comment]
@kchoppin Any ETA on the Laravel 7 dep bump?

**Comment by chris-rr** [comment]
@TerrePorter Just +1ing the request to bump the dep, this currently preventing my Laravel 7 upgrade.

**Comment by ahmad-saad** [comment]
hier is a Temp Package until @TerrePorter bump the dep.

https://packagist.org/packages/enbit/string-blade-compiler

**Comment by TerrePorter** [comment]
Sorry have been extremely busy just now getting back to this

**Comment by TerrePorter** [comment]
@ahmad-saad @chris-rr @zhanang19 I have created a new branch for L7

**Comment by Kwaadpepper** [comment]
Works in Laravel 8 ? :)

**Comment by TerrePorter** [comment]
@Kwaadpepper working on that, but seem to have the same problem in 7.

```ErrorException
strpos() expects parameter 1 to be string, array given ```

has something to do with the factory not loading correctly, which doesn't load the updated view class

**Comment by Kwaadpepper** [comment]
I can already tell you that auto loader is not working.
Doing `composer update` will show packages loaded but not Sbl
**EDIT** Sorry I just saw that I used `4.0` branch. This is why it is not working i guess
