### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by jpscharf** [TerrePorter/StringBladeCompiler#60]
How do you setup an run the test?

## Trying to run tests… ##
1. Checkout the repository.
2. Run `composer install`
3. phpunit is not a dependency
4. `composer require -dev phpunit:^8`
5. `vendor/bin/phpunit`
  - `PHP Warning:  require(/Users/jscharf/Workspace/test/StringBladeCompiler-fork/tests/../../../vendor/autoload.php): failed to open stream: No such file or directory in /Users/jscharf/Workspace/test/StringBladeCompiler-fork/tests/bootstrap.php on line 15`
6. So I modify `tests/bootstrap.php` changing `require __DIR__.'/../../../vendor/autoload.php';` -> `require __DIR__.'/../vendor/autoload.php';
7. `vendor/bin/phpunit`
  - `HP Fatal error:  Uncaught Error: Class 'Wpb\String_Blade_Compiler\Tests\Blade\AbstractBladeTestCase' not found in /Users/jscharf/Workspace/test/StringBladeCompiler-fork/tests/View/Blade/BladeAppendTest.php:5`

- Are the tests up tp date? 
- How am I supposed to run them?

**Comment by TerrePorter** [comment]
I never got all the tests working actually, not much of a TDD developer, although i should be
