### ISSUE TITLE
[5.0.1] Segmentation fault (core dumped) / Maximum function nesting level of '512' reached, aborting!

### ISSUE THREAD

**Issue by veneliniliev** [TerrePorter/StringBladeCompiler#65]
when update to 5.0.1 has this errors:

- Segmentation fault (core dumped) (in console)
- Maximum function nesting level of '512' reached, aborting! (in nginx/apache)

**Comment by TerrePorter** [comment]
bummer, humm.... i had that happen once but it never happened again. I will see what i can figure out

**Comment by TerrePorter** [comment]
@veneliniliev how complex is your template?

**Comment by veneliniliev** [comment]
this errors show before compile template...

**Comment by TerrePorter** [comment]
I am not getting the error here.

try isolating to confirm the error is in stringblade
```
Route::get('/test', function () {
    return view (['template' => '{{$token}}'], ['token' => 'I am the token value']);
});
```
