### ISSUE TITLE
[Version 4.0] Requires restrictive version of Laravel 6.x

### ISSUE THREAD

**Issue by blackdrago** [TerrePorter/StringBladeCompiler#71]
This package is great -- however, I hit a snag when trying to upgrade to Laravel 6.x:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wpb/string-blade-compiler 4 -> satisfiable by wpb/string-blade-compiler[4.0.0].
    - wpb/string-blade-compiler 4.0.0 requires laravel/framework 6.0.* -> found laravel/framework[v6.0.0, ..., v6.0.4] but the package is fixed to v6.20.12 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

The only way to install it is to downgrade from Laravel v6.20.12 to Laravel v6.0.4, which I can't do because it will cause conflicts with some of my other vendor packages.

EDIT: When I tried upgrading to v5.0, composer installs as expected, though I'm seeing errors... will follow up after testing.

**Comment by TerrePorter** [comment]
@blackdrago Sorry for never replying. If your still having problems feel free to post again.
