### ISSUE TITLE
Breaks other packages that contain custom blade directives

### ISSUE THREAD

**Issue by AdamGaskins** [TerrePorter/StringBladeCompiler#73]
I installed [`spatie/laravel-ray`](https://github.com/spatie/laravel-ray) which has a `@ray()` directive for debug output, however the only way I can get this directive to work is by:

1. Adding `spatie/laravel-ray` to my `composer.json`'s `dont-discover`:
  ```json
      "extra": {
          "laravel": {
              "dont-discover": [
                  "spatie/laravel-ray"
              ]
          }
      },
  ```
2. Add the `StringBladeCompilerServiceProvider` to my `app.php` directly after the standard `ViewServiceProvider` (and I comment it out too because it seems to be more consistent that way):
```php
//        Illuminate\View\ViewServiceProvider::class,
        \Wpb\String_Blade_Compiler\StringBladeServiceProvider::class,
```
3. Add the `RayServiceProvider` at the end of my `app.php`
4. Run `php artisan view:clear`

**Comment by danielzzz** [comment]
it breaks also livewire.
@livewireStyles and @livewireScripts don't work with this library

I did the same like you with laravel-ray and it worked for me. thanks!

**Comment by AdamGaskins** [comment]
I made my own similar library that does the same thing without needing to replace the `ViewServiceProvider`. We've been using it in our products at my work this year. [`adamgaskins/view-string`](https://github.com/AdamGaskins/view-string)

**Comment by danielzzz** [comment]
thats cool, thanks!
